language: haskell

ghc:
  - 7.0.4
  - 7.4.2
  - 7.6.3
  - 7.8.4

before_install:
  - export GHCVER=`ghc --numeric-version`

install:
  - cabal update
  - |
    if [ $GHCVER = "7.0.4" ]; then
      cabal install -j --only-dependencies
    else
      cabal install -j --only-dependencies --enable-tests
    fi

script:
  - |
    if [ $GHCVER = "7.0.4" ]; then
      cabal configure
      cabal build
    else
      cabal configure --enable-tests
      cabal build --ghc-option=-Werror
      cabal test
    fi
