# NB: don't set `language: haskell` here

env:
 - CABALVER=1.16 GHCVER=6.12.3
 - CABALVER=1.16 GHCVER=7.0.4
 - CABALVER=1.16 GHCVER=7.2.2
 - CABALVER=1.16 GHCVER=7.4.2
 - CABALVER=1.18 GHCVER=7.6.3
 - CABALVER=1.18 GHCVER=7.8.4
 - CABALVER=1.22 GHCVER=7.10.1

matrix:
  allow_failures:
   - env: CABALVER=head GHCVER=head

before_install:
 - travis_retry sudo add-apt-repository -y ppa:hvr/ghc
 - travis_retry sudo apt-get update
 - travis_retry sudo apt-get install cabal-install-$CABALVER ghc-$GHCVER
 - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH

install:
 - cabal --version
 - echo "$(ghc --version) [$(ghc --print-project-git-commit-id 2> /dev/null || echo '?')]"
 - travis_retry cabal update
 - |
    if [ $GHCVER = "6.12.3" ] || [ $GHCVER = "7.0.4" ] || [ $GHCVER = "7.2.2" ]; then
      cabal install -j --only-dependencies
    else
      cabal install -j --only-dependencies --enable-tests
    fi

script:
 - if [ -f configure.ac ]; then autoreconf -i; fi
 - |
    if [ $GHCVER = "6.12.3" ] || [ $GHCVER = "7.0.4" ] || [ $GHCVER = "7.2.2" ]; then
      cabal configure
      cabal build
    else
      cabal configure --enable-tests -v2
      cabal build --ghc-option=-Werror
      cabal test
 - cabal check
 - cabal sdist

 - export SRC_TGZ=$(cabal info . | awk '{print $2 ".tar.gz";exit}') ;
   cd dist/;
   if [ -f "$SRC_TGZ" ]; then
      cabal install --force-reinstalls "$SRC_TGZ";
   else
      echo "expected '$SRC_TGZ' not found";
      exit 1;
   fi
