clone_folder: "c:\\WORK"

environment:
  global:
    CABOPTS:  "--store-dir=C:\\SR --http-transport=plain-http --enable-tests --enable-benchmarks"
  matrix:
    - GHCVER: "9.2.2"
    - GHCVER: "9.0.2"
    - GHCVER: "8.10.7"
    - GHCVER: "8.8.4.1"
    - GHCVER: "8.6.5"
    - GHCVER: "8.4.4"
    # We deliberately do not test any versions older than GHC 9.4, as GHC 8.2
    # is unable to build text-2.0 on Windows. See the discussion at
    # https://github.com/haskell/text/pull/404.

cache:
 - "C:\\SR"

install:
 - ps: Set-Service wuauserv -StartupType Manual
 - "choco install -y cabal"
 - "choco install -y ghc --version %GHCVER%"
 - "refreshenv"
 - "set PATH=C:\\msys64\\mingw64\\bin;C:\\msys64\\usr\\bin;%PATH%"
 - "cabal --version"
 - "ghc --version"
 - "cabal %CABOPTS% update -v"

build: off

test_script:
 - IF EXIST configure.ac bash -c "autoreconf -i"
 - "cabal %CABOPTS% new-build -j2 --enable-tests --enable-benchmarks all"
 - "cabal %CABOPTS% new-test  -j2 --enable-tests --enable-benchmarks all"
